### ISSUE TITLE
undefined method precompile issue

### ISSUE THREAD

**Issue by bhavinkamani** [dnagir/guard-rails-assets#14]
I am running `rails-assets 0.0.9` on just released `rails 3.1.1`. I am getting following error

```
Booting Rails for test environment.
/Volumes/DATA/beekay/.rvm/gems/ruby-1.9.2-head@rails31/gems/rack-1.3.4/lib/rack/backports/uri/common_192.rb:53: warning: already initialized constant WFKV_
An error occurred compiling assets: undefined method `precompile' for #<Sprockets::StaticCompiler:0x007ff6ab780100>
Failed to compile assets.
```

Here's my guard file. 

``` ruby
guard 'rails-assets' do
  watch(%r{^app/assets/.+$})
end

guard 'jasmine-headless-webkit' do
  watch(%r{^public/assets/.*\.js$})
  watch(%r{^spec/javascripts/.*\.coffee$})
end
```

`rake assets:precompile` is working fine. Not sure if it is similar to https://github.com/dnagir/guard-rails-assets/pull/11.

**Comment by dnagir** [comment]
Please `bundle update guard-rails-assets` and report if there are any issues.
In this version (0.1.1) a new option has been added `:digest => false`. See README.

**Comment by bhavinkamani** [comment]
yep its working fine now... Thanks @dnagir
