### ISSUE TITLE
Allow target to be configurable outside the scope of the public directory

### ISSUE THREAD

**Issue by scottdavis** [dnagir/guard-rails-assets#16]
https://github.com/dnagir/guard-rails-assets/blob/master/lib/guard/rails-assets/rails_runner.rb#L65

Currently I have to add `config.assets.prefix = File.join('../', 'tmp', 'assets')` to my test.rb environment file in order to have the assets compiled for use with jasmine headless webkit without effecting my development environment. The main problem is by compiling them into the public directory the application.js contains all the javascript libraries and rails by default in development mode requires each dependency separately before application.js causing things like jquery to get loaded twice which causes some un expected results in development, yet your tests all pass ( its maddening) 

an option to the guard function world be preferable ex `:target => '/foo'` that would over ride the rails environment setting
or maybe even a note in the guard template reminding you to set the prefix to another location

**Comment by dnagir** [comment]
What is the problem with setting `config.assets.prefix` for test environment?
That's the exact purpose of this option.
Then you just have to configure Jasmine to  load your files from your tmp directory instead of public.

I usually set it to "public/assets-test" instead of a "public/assets" so that test files don't mess with the others.

**Comment by scottdavis** [comment]
Nothing other then the fact that it is scoped to public under the hood I had originally tried to set it via `Rails.root.join('tmp','assets')` but that gave unexpected results since on line 65 of the file above it was being appended to the public path.

**Comment by dnagir** [comment]
It has to in public because it is the only folder that is exposed via the server. So just use "assets-test" prefix.

**Comment by scottdavis** [comment]
regardless a note in the apps guard file would save poor souls like me 30 minutes =(

**Comment by dnagir** [comment]
If this servers the purpose, then feel free to close the issue.

https://github.com/dnagir/guard-rails-assets/commit/2c81cebfc3aa5ef6619e877c929c11e9fa75189c

**Comment by scottdavis** [comment]
works for me thanks
