### ISSUE TITLE
TypeError: can't modify immutable index when starting guard-rails-assets

### ISSUE THREAD

**Issue by nicolasblanco** [dnagir/guard-rails-assets#19]
Hi, this is the exception I get when starting guard with Rails 3.2.1 and 1.9.3 :

<pre>
ERROR: Guard::RailsAssets failed to achieve its <start>, exception was:
TypeError: can't modify immutable index
/Users/nicolas/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/sprockets-2.1.2/lib/sprockets/index.rb:76:in `expire_index!'
/Users/nicolas/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/sprockets-2.1.2/lib/sprockets/base.rb:97:in `cache='
/Users/nicolas/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/guard-rails-assets-0.1.3/lib/guard/rails-assets/rails_runner.rb:34:in `boot_rails'
/Users/nicolas/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/guard-rails-assets-0.1.3/lib/guard/rails-assets/rails_runner.rb:80:in `compile_assets'
/Users/nicolas/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/guard-rails-assets-0.1.3/lib/guard/rails-assets.rb:33:in `compile_assets'
/Users/nicolas/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/guard-rails-assets-0.1.3/lib/guard/rails-assets.rb:15:in `start'
/Users/nicolas/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/guard-1.0.0/lib/guard.rb:369:in `block in run_supervised_task'
/Users/nicolas/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/guard-1.0.0/lib/guard.rb:367:in `catch'
/Users/nicolas/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/guard-1.0.0/lib/guard.rb:367:in `run_supervised_task'
/Users/nicolas/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/guard-1.0.0/lib/guard.rb:195:in `block in start'
/Users/nicolas/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/guard-1.0.0/lib/guard.rb:301:in `block (3 levels) in run_on_guards'
/Users/nicolas/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/guard-1.0.0/lib/guard.rb:300:in `each'
/Users/nicolas/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/guard-1.0.0/lib/guard.rb:300:in `block (2 levels) in run_on_guards'
/Users/nicolas/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/guard-1.0.0/lib/guard.rb:299:in `catch'
/Users/nicolas/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/guard-1.0.0/lib/guard.rb:299:in `block in run_on_guards'
/Users/nicolas/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/guard-1.0.0/lib/guard.rb:298:in `each'
/Users/nicolas/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/guard-1.0.0/lib/guard.rb:298:in `run_on_guards'
/Users/nicolas/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/guard-1.0.0/lib/guard.rb:194:in `start'
/Users/nicolas/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/guard-1.0.0/lib/guard/cli.rb:75:in `start'
/Users/nicolas/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/thor-0.14.6/lib/thor/task.rb:22:in `run'
/Users/nicolas/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/thor-0.14.6/lib/thor/invocation.rb:118:in `invoke_task'
/Users/nicolas/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/thor-0.14.6/lib/thor.rb:263:in `dispatch'
/Users/nicolas/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/thor-0.14.6/lib/thor/base.rb:389:in `start'
/Users/nicolas/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/guard-1.0.0/bin/guard:6:in `<top (required)>'
b/guard:16:in `load'
b/guard:16:in `<main>'
</pre>

**Comment by dnagir** [comment]
I'm not sure what is going on now. Not actually using `guard-rails-assets` much theses days.

I would accept a pull request that fixes this issue.

But in the meanwhile, you can use `:runner => :cli` to avoid the hacks booting Rails (so it will go through the normal assets compilation) process.

**Comment by nicolasblanco** [comment]
thanks i'll test with runner: :cli

**Comment by nicolasblanco** [comment]
OK this works with runner: :cli.

Thanks.

**Comment by dnagir** [comment]
Keep in mind that it's just a workaround (so it boots rails every time something is changed).

I don't think the issue is resolved and I'd love somebody to send a pull request to fix it.

**Comment by nicolasblanco** [comment]
Yeah i know that the issue is still there, but i don't know i'll have the time to look into it...
