### ISSUE TITLE
Guard fails to start when connecting to MongoDB in initializer

### ISSUE THREAD

**Issue by carhartl** [dnagir/guard-rails-assets#8]
I have an initializer in which I connect to a MongoDB like so:

```
MongoHelper.connection = Mongo::Connection.new
```

This causes the following exception:

<pre>
Guard::RailsAssets failed to achieve its <start>, exception was:
RuntimeError: failed to free buffer
/Users/carhartl/.rvm/gems/ruby-1.9.2-p136@tweektv/gems/bson-1.3.1/lib/bson/bson_c.rb:24:in `serialize'
/Users/carhartl/.rvm/gems/ruby-1.9.2-p136@tweektv/gems/bson-1.3.1/lib/bson/bson_c.rb:24:in `serialize'
/Users/carhartl/.rvm/gems/ruby-1.9.2-p136@tweektv/gems/mongo-1.3.1/lib/mongo/cursor.rb:425:in `construct_query_message'
/Users/carhartl/.rvm/gems/ruby-1.9.2-p136@tweektv/gems/mongo-1.3.1/lib/mongo/cursor.rb:405:in `send_initial_query'
/Users/carhartl/.rvm/gems/ruby-1.9.2-p136@tweektv/gems/mongo-1.3.1/lib/mongo/cursor.rb:371:in `refresh'
/Users/carhartl/.rvm/gems/ruby-1.9.2-p136@tweektv/gems/mongo-1.3.1/lib/mongo/cursor.rb:87:in `next_document'
/Users/carhartl/.rvm/gems/ruby-1.9.2-p136@tweektv/gems/mongo-1.3.1/lib/mongo/db.rb:497:in `command'
/Users/carhartl/.rvm/gems/ruby-1.9.2-p136@tweektv/gems/mongo-1.3.1/lib/mongo/connection.rb:704:in `check_is_master'
/Users/carhartl/.rvm/gems/ruby-1.9.2-p136@tweektv/gems/mongo-1.3.1/lib/mongo/connection.rb:504:in `connect'
/Users/carhartl/.rvm/gems/ruby-1.9.2-p136@tweektv/gems/mongo-1.3.1/lib/mongo/connection.rb:656:in `setup'
/Users/carhartl/.rvm/gems/ruby-1.9.2-p136@tweektv/gems/mongo-1.3.1/lib/mongo/connection.rb:101:in `initialize'
/Users/carhartl/Workspace/tweek.tv/config/initializers/mongo.rb:10:in `new'
/Users/carhartl/Workspace/tweek.tv/config/initializers/mongo.rb:10:in `<top (required)>'
</pre>

I could work around by lazily connect...

**Comment by dnagir** [comment]
I don't think there anything that guard-rails-assets can do to establish the connection to MongoDB.

You should have the same issue when you run `bundle exec rake assets:precompile` for the same environment.

The connection should not be established anyway when you just want to compile the assets (especially you don't want it to happen in production).

So lazy connection is the the correct way of solving the problem.

Closing the issue as it doesn't really seem to be related to `guard-rails-assets`.
